-- ASEGURATE QUE EL ID SEA 1 PARA QUE EL USUARIO ADMIN TENGA EL ROL DE ADMINISTRADOR
INSERT INTO public.rol (descripcion, nombre) VALUES('ADMINISTRADOR', 'ADMIN');
-- ASEGURATE QUE EL ID SEA 2 PARA QUE EL USUARIO CLIENTE TENGA EL ROL DE CLIENTE
INSERT INTO public.rol (descripcion, nombre) VALUES('CLIENTE', 'CLIENT');
